#!/usr/bin/env python3

import os
import sys
import argparse
import textwrap
from csv2qif import csv2qif

parser = argparse.ArgumentParser(
    prog='csv2qif',
    formatter_class=argparse.RawTextHelpFormatter,
    description="Convert credit card/banking CSV export files to QIF format.",
    epilog=textwrap.fill("""NOTE: If you provide a 'categories.txt' file in the 
same directory as the csv2qif program, it will automatically be used.  Each line
should have the vendor name, a comma, and then the category to be used when
the payee matches that vendor.  Empty lines are ignored.  A default version of
this file can be kept in the directory of the csv2qif executable.  If a copy
of this file is found in the directory that this command is run in, it
overrides the version in the executable directory.
"""))

parser.add_argument('csvfilename', type=str, nargs='?')
parser.add_argument('--printcats', action="store_true", default=False,
                    help="Print the categories read from the 'categories.txt' file and exit.")
parser.add_argument('--complain', action="store_true", default=False,
                    help="Complain about unknown Payees (to stderr)")

args = parser.parse_args()
print(args)

# Handle optional csvfilename argument
if (args.csvfilename == None) and (not args.printcats):
    parser.error("CSV filename is required!")

csv2qif(args)
